### ISSUE TITLE
Having trouble pulling image

### ISSUE THREAD

**Issue by VasantSachdewa** [agoda-com/docker-emulator-android#3]
I am getting the following error while trying to run docker command
Error:
 Error response from daemon: pull access denied for agoda-com/docker-emulator-android-23, repository does not exist or may require 'docker login'.

**Comment by Malinskiy** [comment]
Hey @VasantSachdewa. 

As mentioned in the [readme](https://github.com/agoda-com/docker-emulator-android#building) you need to build the images first since we can't republish Android SDK components.

I'll close the issue since there is nothing we can do about distributing images at the moment. Feel free to reopen the issue if you have any solutions or open another one if you have another issue.

Cheers

**Comment by VasantSachdewa** [comment]
Thankyou
